// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.ToListAsync_ReturnsListOfLogOperationModels")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.GetByIdAsync_ReturnsLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.UpdateAsync_UpdatesLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.AddAsync_AddsLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.RemoveByIdAsync_RemovesLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.RemoveAsync_RemovesLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.GetById_ReturnsLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.Update_UpdatesLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.ToList_ReturnsListOfLogOperationModels")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.Add_AddsLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.RemoveById_RemovesLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogOperationTests.Remove_RemovesLogOperationModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.Add_AddsLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.AddAsync_AddsLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.GetById_ReturnsLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.GetByIdAsync_ReturnsLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.Remove_RemovesLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.RemoveAsync_RemovesLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.RemoveById_RemovesLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.RemoveByIdAsync_RemovesLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.ToList_ReturnsListOfLogModels")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.ToListAsync_ReturnsListOfLogModels")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.Update_UpdatesLogModel")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~M:FilesSafeReserve.Tests.Repositories.LogRepoTests.UpdateAsync_UpdatesLogModel")]
