# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui-android ios maccatalyst
    - name: Restore dependencies
      run: dotnet restore ./solution.sln
    - name: Build
      run: dotnet build ./solution.sln --no-restore
    - name: Test FSR Domain
      run: dotnet test ./tests/FilesSafeReserve.Domain.Tests/FilesSafeReserve.Domain.Tests.csproj --no-build --verbosity normal
    - name: Test FSR Infrastructure
      run: dotnet test ./tests/FilesSafeReserve.Infra.Tests/FilesSafeReserve.Infra.Tests.csproj --no-build --verbosity normal
